# Generated by Django 2.2.28 on 2023-07-31 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cddfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbcnc', models.ForeignKey(default='Test', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='zass_cbcnc', to='home.Cddfs')),
            ],
        ),
    ]
